# Dockerfile
FROM node:20-alpine

# Установим рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем остальные файлы
COPY . .

# Указываем порт
EXPOSE 1337

# Команда для запуска приложения
CMD ["npm", "run", "start"]
